// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

import {Script, console} from "forge-std/Script.sol";
import {ERC1967Proxy} from "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";
import {Mondeto} from "../src/Mondeto.sol";

contract DeployScript is Script {
    function run() external {
        address[] memory tokens = vm.envAddress("ACCEPTED_TOKENS", ",");
        uint256 initialPrice = vm.envUint("INITIAL_PRICE");
        uint256 minPrice = vm.envUint("MIN_PRICE");
        uint256 halvingTime = vm.envUint("HALVING_TIME_DAYS") * 1 days;
        uint256 feeRate = vm.envUint("INITIAL_FEE_RATE");

        // Load land mask (and dimensions) from JSON file generated by map/generate_land_mask.py
        // or map/generate_continents.py. Defaults to the world map.
        string memory landMaskPath = vm.envOr("LAND_MASK_PATH", string("map/land_mask.json"));
        console.log("Land mask:", landMaskPath);
        string memory json = vm.readFile(landMaskPath);
        uint16 width = uint16(vm.parseJsonUint(json, ".width"));
        uint16 height = uint16(vm.parseJsonUint(json, ".height"));
        uint256[] memory landMask = abi.decode(vm.parseJson(json, ".mask"), (uint256[]));

        vm.startBroadcast();

        // Deploy implementation
        Mondeto implementation = new Mondeto(width, height, halvingTime);
        console.log("Implementation deployed at:", address(implementation));

        // Deploy proxy with land mask included in initialization
        bytes memory initData = abi.encodeCall(Mondeto.initialize, (tokens, initialPrice, minPrice, feeRate, landMask));
        ERC1967Proxy proxy = new ERC1967Proxy(address(implementation), initData);
        console.log("Proxy deployed at:", address(proxy));

        vm.stopBroadcast();
    }
}
