#!/usr/bin/env python3
"""Export Terreno + ERC20 ABIs to the frontend as a typed TypeScript module.

Usage:
    uv run python3 script/export-abi.py [--out PATH]

Reads:
    out/Terreno.sol/Terreno.json   (forge build output)

This emits ABIs only — no addresses. Two things are deliberately left to the
frontend so it isn't tied to a single deployment or token set:
  - The contract address: the frontend chooses its deployment via its own
    config/env (e.g. NEXT_PUBLIC_TERRENO_ADDRESS).
  - The accepted-token set: it changes at any time via addAcceptedToken/
    removeAcceptedToken, so the frontend reads it on-chain (getAcceptedTokens
    / tokenConfig). We only ship a generic ERC20 ABI for whichever token it
    picks.

Writes:
    ../terreno-fe/apps/web/src/lib/contract.ts   (default, or --out)
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = ROOT.parent / "terreno-fe" / "apps" / "web" / "src" / "lib" / "contract.ts"

# Generic ERC20 ABI — the frontend uses this against any accepted stablecoin
# (read on-chain via getAcceptedTokens). decimals/symbol let it render the set.
ERC20_ABI = [
    {
        "type": "function",
        "name": "approve",
        "inputs": [
            {"name": "spender", "type": "address", "internalType": "address"},
            {"name": "amount", "type": "uint256", "internalType": "uint256"},
        ],
        "outputs": [{"name": "", "type": "bool", "internalType": "bool"}],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "allowance",
        "inputs": [
            {"name": "owner", "type": "address", "internalType": "address"},
            {"name": "spender", "type": "address", "internalType": "address"},
        ],
        "outputs": [{"name": "", "type": "uint256", "internalType": "uint256"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "balanceOf",
        "inputs": [
            {"name": "account", "type": "address", "internalType": "address"},
        ],
        "outputs": [{"name": "", "type": "uint256", "internalType": "uint256"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "decimals",
        "inputs": [],
        "outputs": [{"name": "", "type": "uint8", "internalType": "uint8"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "symbol",
        "inputs": [],
        "outputs": [{"name": "", "type": "string", "internalType": "string"}],
        "stateMutability": "view",
    },
]



def main():
    parser = argparse.ArgumentParser(description="Export Terreno ABI to TypeScript")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output .ts path")
    args = parser.parse_args()

    # Read Foundry artifact
    artifact_path = ROOT / "out" / "Terreno.sol" / "Terreno.json"
    if not artifact_path.exists():
        raise SystemExit(f"Artifact not found: {artifact_path}\nRun `forge build` first.")
    artifact = json.loads(artifact_path.read_text())
    abi = artifact["abi"]

    # Format ABI as indented JSON, then wrap in TS
    abi_json = json.dumps(abi, indent=2)
    erc20_json = json.dumps(ERC20_ABI, indent=2)

    ts = f"""\
// Auto-generated by terreno/script/export-abi.py — do not edit by hand.
// Regenerate: cd ../terreno && uv run python3 script/export-abi.py
//
// ABIs only. The frontend supplies the contract address itself via the
// per-map registry in `lib/maps/contracts.ts` — use `getContractByMapId(...)`
// to resolve it. Accepted ERC-20 tokens are discovered on-chain via
// `getAcceptedTokens`.

export const TERRENO_ABI = {abi_json} as const

// Generic ERC20 ABI — works against whichever accepted stablecoin the
// frontend picks (read on-chain via getAcceptedTokens).
export const ERC20_ABI = {erc20_json} as const
"""
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(ts)
    print(f"Wrote {args.out} ({len(abi)} ABI entries, ABIs only)")


if __name__ == "__main__":
    main()
