#!/usr/bin/env python3
"""
Generate land mask from world-map.png.
Samples each 2x2 block center for the 300x150 grid.
Outputs apps/web/src/data/landMask.ts

Re-run whenever the map image changes:
  python3 scripts/generate-land-mask.py
"""

from PIL import Image
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR)
IMG_PATH = os.path.join(ROOT, "apps/web/public/world-map.png")
OUT_PATH = os.path.join(ROOT, "apps/web/src/data/landMask.ts")

GRID_W = 300
GRID_H = 150

def is_water(r, g, b):
    """Classify a pixel as water based on RGB values."""
    # White-ish (background/ocean on many maps)
    if r > 220 and g > 220 and b > 220:
        return True
    # Blue-ish (ocean)
    if b > 170 and r < 160 and g < 180:
        return True
    # Light grey (some map backgrounds)
    if r > 200 and g > 200 and b > 200 and abs(r - g) < 15 and abs(g - b) < 15:
        return True
    return False

def main():
    img = Image.open(IMG_PATH).convert("RGB")
    img_w, img_h = img.size
    print(f"Image: {img_w}x{img_h}")

    scale_x = img_w / GRID_W  # 2.0 for 600x300
    scale_y = img_h / GRID_H

    mask = []
    land_count = 0

    for y in range(GRID_H):
        for x in range(GRID_W):
            # Sample center of each grid cell
            img_x = int(x * scale_x + scale_x / 2)
            img_y = int(y * scale_y + scale_y / 2)
            img_x = min(img_x, img_w - 1)
            img_y = min(img_y, img_h - 1)

            r, g, b = img.getpixel((img_x, img_y))
            land = not is_water(r, g, b)
            mask.append(1 if land else 0)
            if land:
                land_count += 1

    total = GRID_W * GRID_H
    print(f"Land pixels: {land_count} / {total} ({100*land_count/total:.1f}%)")

    # Write TypeScript file
    # Compact format: comma-separated 0/1 values
    lines = []
    for row_y in range(GRID_H):
        start = row_y * GRID_W
        row = mask[start:start + GRID_W]
        lines.append(",".join(str(v) for v in row))

    # Join rows with commas (not just newlines)
    array_body = ",\n".join(lines)

    ts_content = f"""// Auto-generated by scripts/generate-land-mask.py — do not edit manually
// Re-run: python3 scripts/generate-land-mask.py
// 1 = land, 0 = water. Index = y * 300 + x
// Land pixels: {land_count} / {total} ({100*land_count/total:.1f}%)

export const LAND_MASK = new Uint8Array([
{array_body}
])

export const LAND_COUNT = {land_count}
"""

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write(ts_content)

    print(f"Written to {OUT_PATH}")

if __name__ == "__main__":
    main()
